### ISSUE TITLE
Feature Request: Groups of grains (projects)

### ISSUE THREAD

**Issue by zeigerpuppy** [sandstorm-io/sandstorm#1830]
It would be very useful to be able to group grains together, for instance if one has three related etherpad grains and an ethercalc grain, then they could be grouped and shared as one "project".

This would probably be best implemented by a tag and filter system.
The advantages would be considerable:
- ability to sort by project
- makes archiving easier
- grains naturally go together in projects
- tagging allows overlap of projects

I believe this would make the grain handling and sharing more logical overall.

**Comment by neynah** [comment]
Existing grouping/folder discussion here: https://github.com/sandstorm-io/sandstorm/issues/969 and grain management/tagging discussion here: https://github.com/sandstorm-io/sandstorm/issues/364

**Comment by dwrensha** [comment]
Closing, because we have released the Collections app: https://sandstorm.io/news/2016-08-09-collections-app.

**Comment by ocdtrekkie** [comment]
Do we still have an open issue for tags/folders/labels, because Collections doesn't address that.

**Comment by dwrensha** [comment]
There is still https://github.com/sandstorm-io/sandstorm/issues/581

**Comment by ocdtrekkie** [comment]
Wow. 581 has some super classic Sandstorm screenshots.
