### ISSUE TITLE
spk crashes with "Message is too deeply-nested or contains cycles" with an SPK that passes "spk verify"

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2719]
Steps to reproduce:

- Download this particular experimental Rocket.Chat build from the experimental app market - https://apps.sandstorm.io/app/vfnwptfn02ty21w715snyyczw0nqxkv3jvawcah10c6z7hj1hnu0?experimental=true 
- alternatively, see steps below for getting the SPK via wget.

Actual behavior:

- See this image:

![](https://cloud.githubusercontent.com/assets/855341/19869596/34fd9122-9f6a-11e6-878b-1c76575ce59d.png)

- See this in server log:

```
*** Uncaught exception ***
capnp/layout.c++:2909: failed: expected nestingLimit > 0; Message is too deeply-nested or contains cycles.  See capnp::ReaderOptions.
stack: 0x5fa641 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1
capnp/rpc.c++:123: info: returning failure over rpc; exception = sandstorm/util.c++:959: failed: expected exitCode == 0; child process failed; name = spk; exitCode = 1
stack: 0x5aa118 0x5a9e8b 0x4a59a2 0x43d170
Failed to install app: Error: remote exception: expected exitCode == 0; child process failed; name = spk; exitCode = 1 at Error (native)
```

Expected behavior:

- App installs OK, or alternatively, `spk verify` fails.

Other notes:

- Here's how to download the SPK via wget.

```
paulproteus@rose:/tmp$ wget https://app-index.sandstorm.io/packages/aa7a8a60fe3eb9345a3510d04af44d3e  
--2016-10-31 19:59:44--  https://app-index.sandstorm.io/packages/aa7a8a60fe3eb9345a3510d04af44d3e
Resolving app-index.sandstorm.io (app-index.sandstorm.io)... 107.178.223.140
Connecting to app-index.sandstorm.io (app-index.sandstorm.io)|107.178.223.140|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 90523192 (86M) [application/octet-stream]
Saving to: ‘aa7a8a60fe3eb9345a3510d04af44d3e’
 
aa7a8a60fe3eb9345a3510d04a 100%[=======================================>]  86.33M  6.67MB/s   in 12s    
 
2016-10-31 19:59:56 (7.35 MB/s) - ‘aa7a8a60fe3eb9345a3510d04af44d3e’ saved [90523192/90523192]
```

- Here's me successfully verifying it:

```
paulproteus@rose:/tmp$ spk verify aa7a8a60fe3eb9345a3510d04af44d3e
 
{ "appId": "vfnwptfn02ty21w715snyyczw0nqxkv3jvawcah10c6z7hj1hnu0",
  "packageId": "aa7a8a60fe3eb9345a3510d04af44d3e",
  "title": {"defaultText": "Rocket.Chat"},
  "version": 45,
  "marketingVersion": {"defaultText": "0.45.0-develop"},
  "authorPgpKeyFingerprint": "5C5580353165D42FD89E1371A9FF0AD7DEE40258",
  "metadata": {
    "icons": {"appGrid": {"svg": LargeTextBlob(2509)}, "grain": {"svg": LargeTextBlob(1706)}, "market": {"svg": LargeTextBlob(1914)}},
    "website": "https:\/\/rocket.chat",
    "codeUrl": "https:\/\/github.com\/RocketChat\/Rocket.Chat",
    "license": {"openSource": "mit"},
    "categories": ["communications", "productivity", "office", "social", "developerTools"],
    "author": {"contactEmail": "team@rocket.chat", "pgpSignature": LargeDataBlob(688), "upstreamAuthor": "Rocket.Chat"},
    "pgpKeyring": LargeDataBlob(8435),
    "description": {"defaultText": LargeTextBlob(281)},
    "shortDescription": {"defaultText": "Chat app"},
    "screenshots": [
      {"width": 1024, "height": 696, "png": LargeDataBlob(40830)},
      {"width": 1024, "height": 696, "png": LargeDataBlob(60942)},
      {"width": 1024, "height": 696, "png": LargeDataBlob(71990)},
      {"width": 1024, "height": 696, "png": LargeDataBlob(219976)} ],
    "changeLog": {"defaultText": "### FIRST Sandstorm VERSION of Rocket.Chat\n"} } }
```

**Comment by paulproteus** [comment]
Weirdly this is an infinite loop:

```
stack: 0x5fa641 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1 0x5facc1
```

Is there a way for me to get symbols from `spk`?

**Comment by paulproteus** [comment]
@kentonv did some research on this yesterday. It relates to path components `thing1/thing2/thing3` that exceed 64 levels of depth, which the Rocket.Chat app does with a ~320 byte path name in `node_modules`.

I believe he was going to ask @dwrensha to work on it. Did that happen? If so, @dwrensha would you self-assign if you accept?

**Comment by dwrensha** [comment]
Heard in meeting today: the path in question is exactly one component deeper than the default limit of 64. We could up the limit in `spk unpack`, but first we want to make sure rocket.chat actually needs it, as it appears that this SPK includes a bunch of unneeded dev dependencies.

**Comment by paulproteus** [comment]
I personally believe that we should fix the issue on our end, and *then*
ask the Rocket.Chat people what's wrong with their build process.

Rationale:

- If we take the time to accept this SPK, we'll have spent about 30-90
engineering minutes on increasing this limit, and we can then deliver this
Rocket.Chat build to our users about 1 week from today.

- If we try to fix the Rocket.Chat build, it'll take about 5-8 engineering
hours, spread between us and the Rocket.Chat team, and the value to our
users will be exactly the same as above.

Therefore it seems a poor trade-off to pick the latter option. Given that,
my opinion is we should ship the fix that makes their existing SPK work
ASAP.

Happy to hear other thoughts, though. Perhaps I'm misunderstanding the
trade-offs, or perhaps other people have other priorities.

**Comment by kentonv** [comment]
To be clear on my position here:

* I think if the rocket.chat spk is not fixed before the next release, we should definitely increase the limit in that release.
* If we could push a hotfix release to up the limit, I would probably do that. Unfortunately, the nature of the problem is such that a full release is required.
* I will update Testrock now so that we can at least test the SPK.

However, in general, I am extremely reluctant to accept the argument that the right response to problems of excessive bloat is to increase the limits that said bloat is violating and move on. We have uncovered a real bug here. This bug could be having real impact on users, by increasing download sizes (yes, this matters: look at the tek linux Sandstorm video where they complained about how much time they spent waiting for apps to download!) and possibly startup time (which is currently really, really bad for rocket.chat).

**Comment by kentonv** [comment]
The new spk now works on testrock.

**Comment by kentonv** [comment]
Fixed by #2735 (will roll out this weekend).

**Comment by dwrensha** [comment]
I confirm that this is fixed in the latest release.
